---
title: "Baseball Rainouts"
author: "Sean Mussenden | Howard Center for Investigative Journalism"
date: "10/22/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load Libraries

```{r}
library(tidyverse)  # attaches purrr and readr
library(fs)
library(lubridate)
library(rvest)
library(stringr)
library(downloader)
```


## Scrape Orioles Game Logs

```{r}
library(tidyverse)  # attaches purrr and readr
library(fs)
library(lubridate)
library(rvest)
library(stringr)
library(downloader)
library(RVerbalExpressions)
```

```{r}

# Get List of 3 Digit Codes for Current Teams
teams <- read_html("https://www.retrosheet.org/boxesetc/MISC/FRDIR.htm")
teams <- teams %>%
  html_nodes("a") %>%
  html_attr("href") %>%
  str_subset("FR_") %>%
  head(n=31) %>%
  str_replace("^.././FR_","") %>%
  str_replace(".htm$","") %>%
  # For testing, just get Baltimore
  str_subset("BAL")

#print(teams)

# Get List of Years

# years <- c("1919", "1920","1921","1922","1923","1924","1925","1926","1927","1928","1929","1930","1931","1932","1933","1934","1935","1936","1937","1938","1939", "1940","1941","1942","1943","1944","1945","1946","1947","1948","1949","1950","1951","1952","1953","1954","1955","1956","1957","1958","1959","1960","1961","1962","1963","1964","1965","1966","1967","1968","1969","1970","1971","1972","1973","1974","1975","1976","1977","1978","1979","1980","1981","1982","1983","1984","1985","1986","1987","1988","1989","1990","1991","1992","1993","1994","1995","1996","1997","1998","1999","2000","2001","2002","2003","2004","2005","2006","2007","2008","2009","2010","2011","2012","2013","2014","2015","2016","2017","2018")

# Years just for orioles
 years <- c("1954","1955","1956","1957","1958","1959","1960","1961","1962","1963","1964","1965","1966","1967","1968","1969","1970","1971","1972","1973","1974","1975","1976","1977","1978","1979","1980","1981","1982","1983","1984","1985","1986","1987","1988","1989","1990","1991","1992","1993","1994","1995","1996","1997","1998","1999","2000","2001","2002","2003","2004","2005","2006","2007","2008","2009","2010","2011","2012","2013","2014","2015","2016","2017","2018")

# Years for debugging
# years <- c("2018", "2017")

# Build List of schedule URLS for each year for each team, which should return a single HTML page with the schedule and links to individual games

# Create the empty list
schedule_url <- vector()

# For loop to get URls
for (team in teams) {
  for (year in years) {
  temp <- paste0("https://www.retrosheet.org/boxesetc/", year, "/V", team, "0", year,".htm")
  schedule_url <- append(schedule_url, list(temp))
}
} 
# Build a list of games URLs to scrape
games_url <- vector()
for (url in schedule_url) {
  
  team_code <- str_sub(url, 43, 45)

  temp <- read_html(url) %>%
  html_nodes("a") %>%       # find all links
  html_attr("href") %>%
  str_subset("/B0") %>%
  str_subset(team_code) %>%
  str_replace("../", "https://www.retrosheet.org/boxesetc/") 
  
  games_url <- append(games_url, temp)

} 

# Pull down html files for each team for each year
for (url in games_url) {
    # Download each file into download folder, store it as a single zip file called a.zip that will be overwritten. 
    filename <- str_sub(url, 42, 58)
    year <- str_sub(url,51,54)
    # print(year)
    #print(filename)
    download(url, dest=paste0("../data/html/", year,"/", filename), mode="wb") %>%
    Sys.sleep(10)  
}

#for (i in 1919:2019) {
#  dir.create(paste0("../data/html/",i))
#}


```



## Scrape zip files from retrosheet

```{r}

# Store the retrosheet link as an object
page <- read_html("https://www.retrosheet.org/schedule/index.html")

# Get a list of all of the links to the ZIP files to download

page <- page %>%
  html_nodes("a") %>%       # find all links
  html_attr("href") %>%     # get the url
  str_subset("\\.ZIP")      # of links that end in .ZIP

# For loop to download each zipfile and unzip it into a folder as a text file. 
for (url in page) {
    # Download each file into download folder, store it as a single zip file called a.zip that will be overwritten. 
    download(url, dest="../data/download/a.zip", mode="wb") 
    # Unzip each file into the unzip folder. 
    unzip ("../data/download/a.zip", exdir = "../data/unzipped")
}
```

```{r}

# Create an object with data directory path
data_dir <- "../data/unzipped"

# Use FS Package to store list of files in my directory as a vector
txt_files <- dir_ls(data_dir)

# Read in all year data
data <- txt_files %>% 
  map_dfr(read_csv, col_names=c(
        "date",
        "game_no",
        "day",
        "visit_team",
        "visit_league",
        "visit_season_game_no",
        "home_team",
        "home_league",
        "home_season_game_no",
        "time_of_day",
        "cancel_postpone_indicate",
        "makeup_date"),
        col_types = cols(
          date = col_double(),
          game_no = col_double(),
          day = col_character(),
          visit_team = col_character(),
          visit_league = col_character(),
          visit_season_game_no = col_double(),
          home_team = col_character(),
          home_league = col_character(),
          home_season_game_no = col_character(),
          time_of_day = col_character(),
          cancel_postpone_indicate = col_character(),
          makeup_date = col_double()
        )
        )

```

## Cleaning

```{r}
glimpse(data)

data_x <- data %>%
  mutate(date = ymd(date), makeup_date = ymd(date)) %>%
  mutate(year = year(date)) %>%
  mutate(month = month(date))

year_check <- data_x %>%
  group_by(year) %>%
  summarise(count=n())

postpone_check <- data_x %>%
  group_by(cancel_postpone_indicate) %>%
  summarise(count=n())

teams <- data_x %>%
  group_by(home_team) %>%
  summarise(count=n()) %>%
  arrange(home_team)

```

### Analysis by Year 
```{r}
# Create a subset of the last 100 years
data_x <- data_x %>%
  filter(year > 1920) %>%
  # Add a line to filter for specific years
  filter(home_team == "BAL")

#STL, ANAHEIM, CARDINALS, METS, PHILLY, DETROIT, DENVER, LAD, BOSTON,RANGERS (TEXAS), CIN, WHITE SOX, KC, SF, SD, PITT, CLEVE


# Create a total_games by year dataframe

total_games_year <- data_x %>%
  group_by(year) %>%
  summarise(count=n()) %>%
  arrange(year) %>%
  filter(!is.na(year))

# Filter data set to create a list of rain postponed games by year

#weather_postponed_games <- data_x %>%
#  filter(str_detect(str_to_lower(cancel_postpone_indicate),"rain|snow|hurricane|inclement|threatening|wet|flood"))
weather_postponed_games <- data_x %>%
  filter(str_detect(str_to_lower(cancel_postpone_indicate),"rain"))

# Data frame of rain postponed games by year

weather_postponed_games_year <- weather_postponed_games %>%
  group_by(year) %>%
  summarise(count=n()) %>%
  arrange(year) %>%
  filter(!is.na(year))

# Join the two dataframes together and calculate percentage

pct_weather_postponed_year <- weather_postponed_games_year %>%
  inner_join(total_games_year, by="year") %>%
  rename(total=count.y, postponed=count.x) %>%
  mutate(pct_postponed = (postponed/total)*100)




view(pct_weather_postponed_year)

```

### Analysis by Month and Year 
```{r}
# Create a subset of the last 100 years
data_x <- data_x %>%
  filter(year > 1920) %>%
  # Add a line to filter for specific years
  filter(home_team == "BAL")

# Create a total_games by year dataframe

total_games_month_year <- data_x %>%
  group_by(month, year) %>%
  summarise(count=n()) %>%
  arrange(year, month) %>%
  filter(!is.na(year))

# Filter data set to create a list of rain postponed games by year

weather_postponed_games <- data_x %>%
  filter(str_detect(str_to_lower(cancel_postpone_indicate),"rain|snow|hurricane|inclement|threatening|wet|flood"))

# Data frame of rain postponed games by year

weather_postponed_games_month_year <- weather_postponed_games %>%
  group_by(month, year) %>%
  summarise(count=n()) %>%
  arrange(year, month) %>%
  filter(!is.na(year))

# Join the two dataframes together and calculate percentage

pct_weather_postponed_month_year <- weather_postponed_games_month_year %>%
  inner_join(total_games_month_year, by=c("year","month")) %>%
  rename(total=count.y, postponed=count.x) %>%
  mutate(pct_postponed = (postponed/total)*100)




view(pct_weather_postponed_month_year)

```